setwd("C:/Users/rossh/Classwork/Challenges_and_Projects/MechaCar_Statistical_Analysis")
library(dplyr)
mech_df <- read.csv(file='MechaCar_mpg.csv',check.names=F,stringsAsFactors = F)
View(mech_df)
lm(formula = mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data = mech_df)
summary(lm(formula = mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data = mech_df))
suspension_df <- read.csv(file='Suspension_Coil.csv', check.names=F, stringsAsFactors = F)
View(suspension_df)
total_summary <- suspension_df %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI), .groups = 'keep')
View(total_summary)
lot_summary <- suspension_df %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI), .groups = 'keep')
View(lot_summary)
t.test(log10(suspension_df$PSI),mu=mean(log10(total_summary$Mean)))
t.test(log10(suspension_df$PSI),mu=mean(log10(subset(lot_summary,Manufacturing_Lot='Lot1')$Mean)))
t.test(log10(suspension_df$PSI),mu=mean(log10(subset(lot_summary,Manufacturing_Lot='Lot2')$Mean)))
t.test(log10(suspension_df$PSI),mu=mean(log10(subset(lot_summary,Manufacturing_Lot='Lot3')$Mean)))